'use client';
import { useState } from 'react';
import { formatDate } from '@/src/domain/calculations';
import { UnambiguousDateInput } from '@/src/components/ui/forms';
import { Button } from '@/src/components/ui/actions';
import { Alert } from '@/src/components/ui/feedback';
import { Modal } from '@/src/components/ui/overlays';
import { EXPENSE_ALLOCATION_BASIS, EXPENSE_TODAY, type ExpenseDraft, type ExpenseListItem, type ExpenseWorkspace } from '@/src/domain/expenses';
import { shiftIsoDate } from '@/src/domain/financial-calculations';
import type { ExpenseScope } from '@/src/domain/models';
import type { useExpenses } from '@/src/services/hooks/use-expenses';

export const sourceMoney = (amount: number, currency = 'GBP') => new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(amount / 100);
export const scopeTypeLabel = (type: ExpenseScope['type']) => ({ organisation: 'Organisation', company: 'Company', marketplace: 'Marketplace', marketplace_account: 'Marketplace Account', product: 'Product' })[type];
type Hook = ReturnType<typeof useExpenses>;

export function ExpenseEditor({ item, workspace, hook, onClose, onSaved }: { item?: ExpenseListItem; workspace: ExpenseWorkspace; hook: Hook; onClose: () => void; onSaved: (id: string) => void }) {
  const initialScope = item?.version.scope ?? workspace.scopeOptions[0]?.scope ?? { type: 'organisation' };
  const [draft, setDraft] = useState<ExpenseDraft>({ name: item?.expense.name ?? '', category: item?.expense.category ?? 'Software & subscriptions', type: item?.expense.type ?? 'recurring', sensitive: item?.expense.sensitive ?? false, amountMinor: item?.version.amountMinor ?? 30000, currency: item?.version.currency ?? 'GBP', scope: initialScope, effectiveFrom: item && (item.expense.type === 'one-off' || item.version.effectiveFrom > EXPENSE_TODAY) ? item.version.effectiveFrom : EXPENSE_TODAY, endDate: item?.expense.type === 'recurring' && item.version.effectiveTo && item.version.effectiveTo > EXPENSE_TODAY ? shiftIsoDate(item.version.effectiveTo, -1) : undefined, source: '', reason: '', confirmed: false, backdatedConfirmed: false });
  const [amount, setAmount] = useState(String(draft.amountMinor / 100));
  const [preview, setPreview] = useState(false);
  const [localError, setLocalError] = useState('');
  const requiresHistorical = draft.effectiveFrom < EXPENSE_TODAY || item?.expense.type === 'one-off' && item.version.effectiveFrom < EXPENSE_TODAY;
  const patch = <K extends keyof ExpenseDraft>(key: K, value: ExpenseDraft[K]) => { setDraft((current) => ({ ...current, [key]: value, confirmed: false, backdatedConfirmed: false })); setPreview(false); setLocalError(''); };
  const scopeOptions = workspace.scopeOptions.filter((option) => option.scope.type === draft.scope.type);
  const valid = draft.name.trim() && draft.category.trim() && draft.amountMinor > 0 && Number.isSafeInteger(draft.amountMinor) && draft.effectiveFrom && draft.source.trim() && draft.reason.trim();
  async function save() { try { const result = await hook.save.mutateAsync({ draft, id: item?.id }); onSaved(result.id); } catch { /* Mutation error is rendered. */ } }
  return <Modal open onOpenChange={(open) => { if (!open && !hook.busy) onClose(); }} title={item ? 'Update Expense' : 'Create Expense'} description="Review the financial basis, effective period and allocation before confirming." footer={preview ? <Button variant="primary" loading={hook.busy} disabled={!draft.confirmed || Boolean(requiresHistorical && !draft.backdatedConfirmed)} onClick={save}>{hook.busy ? 'Recalculating profitability' : item ? 'Confirm update' : 'Create expense'}</Button> : <Button variant="primary" onClick={() => { if (valid) setPreview(true); else setLocalError('Complete the required fields and enter an amount greater than zero.'); }}>Review expense</Button>}>
    <div className="expense-editor">
      {preview ? <>
        <section className="expense-preview" aria-label="Expense financial preview"><p className="eyebrow">Financial preview</p><h3>{draft.name}</h3><strong className="expense-preview-amount">{sourceMoney(draft.amountMinor, draft.currency)}{draft.type === 'recurring' ? ' / month' : ''}</strong><dl><div><dt>Scope</dt><dd>{scopeTypeLabel(draft.scope.type)} · {workspace.scopeOptions.find((option) => option.value === JSON.stringify(draft.scope))?.label ?? 'Unknown scope'}</dd></div><div><dt>{draft.type === 'recurring' ? 'Effective from' : 'Expense date'}</dt><dd>{formatDate(draft.effectiveFrom)}{draft.endDate ? ` to ${formatDate(draft.endDate)}` : ''}</dd></div><div><dt>Allocation basis</dt><dd>{EXPENSE_ALLOCATION_BASIS}</dd></div><div><dt>Source / reason</dt><dd>{draft.source} · {draft.reason}</dd></div></dl><p>This preview shows the configured financial input. Actual allocation depends on eligible canonical transactions on each occurrence date.</p><Button size="compact" onClick={() => { setPreview(false); setDraft((current) => ({ ...current, confirmed: false, backdatedConfirmed: false })); }}>Back to details</Button></section>
        {item ? <Alert title="Effective-dated update">Current {sourceMoney(item.version.amountMinor, item.version.currency)}. {item.expense.type === 'recurring' ? 'Earlier reporting periods retain the previous expense amount outside the chosen effective range.' : 'This correction replaces the applied one-off occurrence. The original remains in History and Activity.'}</Alert> : null}
        {requiresHistorical ? <Alert tone="warning" title="Historical profitability may change">The affected period begins {formatDate(item?.expense.type === 'one-off' && item.version.effectiveFrom < draft.effectiveFrom ? item.version.effectiveFrom : draft.effectiveFrom)}{draft.endDate ? ` and ends ${formatDate(draft.endDate)}` : draft.type === 'one-off' ? `; the corrected occurrence is on ${formatDate(draft.effectiveFrom)}` : ' and continues until the next version or end date'}. The original evidence remains in expense history.</Alert> : null}
        <label className="expense-check"><input type="checkbox" checked={draft.confirmed} onChange={(event) => setDraft((current) => ({ ...current, confirmed: event.target.checked }))} />I have reviewed the amount, scope and effective date.</label>
        {requiresHistorical ? <label className="expense-check"><input type="checkbox" checked={draft.backdatedConfirmed} onChange={(event) => setDraft((current) => ({ ...current, backdatedConfirmed: event.target.checked }))} />I confirm this correction may change historical profitability for the affected period.</label> : null}
      </> : <>
        <fieldset><legend>Expense information</legend><div className="expense-form-grid"><label className="wide">Expense name<input required value={draft.name} onChange={(event) => patch('name', event.target.value)} placeholder="Marketplace analytics subscription" /></label><label>Category<input required list="expense-categories" value={draft.category} onChange={(event) => patch('category', event.target.value)} /><datalist id="expense-categories">{workspace.categories.map((category) => <option key={category} value={category} />)}</datalist></label><label>Type<select value={draft.type} disabled={Boolean(item)} onChange={(event) => patch('type', event.target.value as ExpenseDraft['type'])}><option value="recurring">Recurring</option><option value="one-off">One-off</option></select></label>{hook.canViewSensitive ? <label>Sensitivity<select disabled={Boolean(item)} value={draft.sensitive ? 'sensitive' : 'standard'} onChange={(event) => patch('sensitive', event.target.value === 'sensitive')}><option value="standard">Standard</option><option value="sensitive">Sensitive</option></select></label> : null}</div></fieldset>
        <fieldset><legend>Amount and scope</legend><div className="expense-form-grid"><label>Amount<input required type="number" min="0.01" step="0.01" value={amount} onChange={(event) => { setAmount(event.target.value); patch('amountMinor', Math.round(Number(event.target.value) * 100)); }} /></label><label>Currency<select value={draft.currency} onChange={(event) => patch('currency', event.target.value as ExpenseDraft['currency'])}><option>GBP</option><option>EUR</option><option>USD</option></select></label><label>Scope type<select value={draft.scope.type} onChange={(event) => { const option = workspace.scopeOptions.find((option) => option.scope.type === event.target.value); if (option) patch('scope', option.scope); }}>{([...new Set(workspace.scopeOptions.map((option) => option.scope.type))]).map((type) => <option key={type} value={type}>{scopeTypeLabel(type)}</option>)}</select></label><label>Scoped entity<select value={JSON.stringify(draft.scope)} onChange={(event) => patch('scope', JSON.parse(event.target.value) as ExpenseScope)}>{scopeOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div></fieldset>
        <fieldset><legend>Timing</legend><div className="expense-form-grid"><label>{draft.type === 'recurring' ? 'Effective from' : 'Expense date'}<UnambiguousDateInput aria-label={draft.type === 'recurring' ? 'Effective from' : 'Expense date'} required value={draft.effectiveFrom} onChange={(event) => patch('effectiveFrom', event.target.value)} /></label>{draft.type === 'recurring' ? <label>End date (optional)<UnambiguousDateInput aria-label="End date (optional)" min={draft.effectiveFrom} value={draft.endDate ?? ''} onChange={(event) => patch('endDate', event.target.value || undefined)} /></label> : null}</div><p>{draft.type === 'recurring' ? 'Monthly: full charge on the billing day, clamped for short months. Amount updates retain the original billing day. No daily proration.' : 'A one-off expense occurs only on its expense date.'}</p></fieldset>
        <fieldset><legend>Governance</legend><div className="expense-form-grid"><label className="wide">Source<input required value={draft.source} onChange={(event) => patch('source', event.target.value)} placeholder="Supplier invoice / contract reference" /></label><label className="wide">Reason / note<textarea required rows={2} value={draft.reason} onChange={(event) => patch('reason', event.target.value)} placeholder="Explain the financial change" /></label></div></fieldset>
      </>}
      {localError || hook.save.error ? <Alert tone="negative" title="Expense could not be saved">{localError || hook.save.error?.message}</Alert> : null}
      {hook.busy ? <Alert title="Recalculating profitability">Applying the confirmed expense version to canonical profitability and refreshing reports.</Alert> : null}
    </div>
  </Modal>;
}

export function EndExpenseDialog({ item, hook, onClose, onSaved }: { item: ExpenseListItem; hook: Hook; onClose: () => void; onSaved: () => void }) {
  const [endDate, setEndDate] = useState(EXPENSE_TODAY); const [reason, setReason] = useState(''); const [confirmed, setConfirmed] = useState(false); const [backdatedConfirmed, setBackdatedConfirmed] = useState(false);
  return <Modal open onOpenChange={(open) => { if (!open && !hook.busy) onClose(); }} title="End Expense" description="Choose the last eligible day. Historical financial evidence remains available." footer={<Button variant="danger" disabled={!confirmed || !reason.trim() || endDate < EXPENSE_TODAY && !backdatedConfirmed} loading={hook.busy} onClick={async () => { try { await hook.end.mutateAsync({ id: item.id, endDate, reason, confirmed, backdatedConfirmed }); onSaved(); } catch { /* Error shown below. */ } }}>Confirm end expense</Button>}><div className="expense-editor"><h3>{item.expense.name}</h3><p>{sourceMoney(item.version.amountMinor, item.version.currency)} / month · {item.scopeLabel}</p><label>End date<UnambiguousDateInput aria-label="End date" value={endDate} onChange={(event) => { setEndDate(event.target.value); setConfirmed(false); setBackdatedConfirmed(false); }} /></label><label>Reason<textarea value={reason} onChange={(event) => { setReason(event.target.value); setConfirmed(false); }} /></label><p>No occurrence will be applied from {endDate ? formatDate(shiftIsoDate(endDate, 1)) : 'the following day'}. Earlier periods retain their evidence.</p>{endDate < EXPENSE_TODAY ? <><Alert tone="warning" title="Historical profitability may change">Occurrences after {endDate ? formatDate(endDate) : 'the chosen date'} will be withdrawn from profitability.</Alert><label className="expense-check"><input type="checkbox" checked={backdatedConfirmed} onChange={(event) => setBackdatedConfirmed(event.target.checked)} />I confirm the historical impact of ending this expense.</label></> : null}<label className="expense-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />I have reviewed and confirm the end date and financial impact.</label>{hook.end.error ? <Alert tone="negative" title="Expense could not be ended">{hook.end.error.message}</Alert> : null}{hook.busy ? <Alert title="Recalculating profitability" /> : null}</div></Modal>;
}
