'use client';
import Link from 'next/link';
import { formatDate } from '@/src/domain/calculations';
import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { createColumnHelper } from '@tanstack/react-table';
import { useAnalysisContext } from '@/src/components/providers/analysis-context-provider';
import { AccessState } from '@/src/components/rbac/access';
import { PageHeader } from '@/src/components/product/patterns';
import { EnterpriseDataGrid, gridFeatures } from '@/src/components/tables/enterprise-data-grid';
import { EmptyState, ErrorState, PageSkeleton } from '@/src/components/states/states';
import { Button } from '@/src/components/ui/actions';
import { Alert, Badge, useToast } from '@/src/components/ui/feedback';
import { Breadcrumbs } from '@/src/components/ui/navigation';
import { EXPENSE_ALLOCATION_BASIS, type ExpenseAllocationRow, type ExpenseVersion } from '@/src/domain/expenses';
import { shiftIsoDate } from '@/src/domain/financial-calculations';
import { expenseReportingMinor } from '@/src/services/analytics/analytics-aggregation';
import { useExpenses } from '@/src/services/hooks/use-expenses';
import { EndExpenseDialog, ExpenseEditor, scopeTypeLabel, sourceMoney } from './expense-editor';
import { expensePeriod, ExpenseStatusBadge } from './expenses-page';
import './expenses.css';

const allocationColumn = createColumnHelper<typeof gridFeatures, ExpenseAllocationRow>();
const tabs = ['overview', 'allocation', 'history', 'activity'] as const;
type Tab = typeof tabs[number];
const actorName = (value: unknown) => typeof value === 'object' && value !== null && 'actorName' in value && typeof value.actorName === 'string' ? value.actorName : 'Recorded actor';
const eventLabel = (action: string) => ({ 'expense.created': 'Expense created', 'expense.updated': 'Expense updated', 'expense.ended': 'Expense ended', 'expense.backdated': 'Backdated correction' })[action] ?? action.replaceAll('.', ' ');

export function ExpenseDetailPage({ expenseId }: { expenseId: string }) {
  const { workspace, context } = useAnalysisContext(); const searchParams = useSearchParams(); const { showToast } = useToast();
  const [tab, setTab] = useState<Tab>(() => tabs.includes(searchParams.get('tab') as Tab) ? searchParams.get('tab') as Tab : 'overview');
  const [editing, setEditing] = useState(false); const [ending, setEnding] = useState(false);
  const hook = useExpenses({}, expenseId); const item = hook.detailQuery.data;
  const base = `/o/${workspace.organisation.slug}`; const params = new URLSearchParams(searchParams.toString()); params.delete('tab');
  const link = (path: string) => `${base}/${path}?${params}`;
  const currency = workspace.organisation.reportingCurrency;
  const allocationColumns = [allocationColumn.accessor('occurredOn', { header: 'Date', size: 120, cell: ({ getValue }) => formatDate(getValue()) }), allocationColumn.accessor('company', { header: 'Company', size: 190 }), allocationColumn.accessor('marketplace', { header: 'Marketplace', size: 125, cell: ({ getValue }) => ({ amazon: 'Amazon', ebay: 'eBay', temu: 'Temu' } as Record<string, string>)[getValue().toLowerCase()] ?? getValue() }), allocationColumn.accessor('account', { header: 'Account', size: 210 }), allocationColumn.accessor('product', { header: 'Product', size: 260, cell: ({ row }) => <Link className="expense-name" href={link(`products/${encodeURIComponent(row.original.productId)}`)}>{row.original.product}</Link> }), allocationColumn.accessor('eligibleNetRevenueMinor', { header: 'Eligible Net Revenue', size: 170, cell: ({ getValue }) => <span className="numeric">{sourceMoney(getValue(), currency)}</span> }), allocationColumn.accessor('allocatedMinor', { header: 'Allocated expense', size: 160, cell: ({ getValue }) => <span className="numeric">{sourceMoney(getValue(), currency)}</span> })];
  const scopeFor = (version: ExpenseVersion) => hook.query.data?.scopeOptions.find((option) => option.value === JSON.stringify(version.scope))?.label ?? scopeTypeLabel(version.scope.type);
  if (!hook.access.allowed) return <AccessState decision={hook.access} />;
  if (hook.detailQuery.isPending) return <PageSkeleton />;
  if (hook.detailQuery.isError) return <ErrorState title="Expense could not be loaded" description={hook.detailQuery.error.message} onRetry={() => hook.detailQuery.refetch()} />;
  if (!item) return <EmptyState title="Expense not found" description="This expense is unavailable in your authorised scope." actions={<Link className="secondary-button" href={link('expenses')}>Back to Expenses</Link>} />;
  return <div className="expenses-page"><Breadcrumbs items={[{ label: workspace.organisation.name, href: link('dashboard') }, { label: 'Expenses', href: link('expenses') }, { label: item.expense.name }]} /><PageHeader eyebrow="Expense detail" title={item.expense.name} description={`${item.expense.category} · ${scopeTypeLabel(item.version.scope.type)} · ${item.scopeLabel}`} actions={<><ExpenseStatusBadge item={item} />{hook.canEdit ? <><Button disabled={hook.busy || !hook.query.data} onClick={() => { hook.save.reset(); setEditing(true); }}>Edit / Update Amount</Button>{item.expense.type === 'recurring' && item.status !== 'ended' ? <Button disabled={hook.busy} onClick={() => { hook.end.reset(); setEnding(true); }}>End Expense</Button> : null}</> : <Badge>Read only</Badge>}</>} />
    {hook.query.data?.sensitiveRestricted ? <Alert title="Partial expense visibility">Only authorised expense evidence and allocations are available. Full profitability may be restricted.</Alert> : null}
    {item.needsReview ? <Alert tone="warning" title="Unallocated Expense">{sourceMoney(item.unallocatedMinor, currency)} has no eligible transaction on its occurrence date. This amount is retained in the expense ledger and has not been spread into unrelated periods or products.</Alert> : null}
    <section className="expense-summary expense-detail-summary" aria-label="Expense financial summary"><div><span>Source amount</span><strong>{sourceMoney(item.version.amountMinor, item.version.currency)}</strong><small>{item.expense.type === 'recurring' ? 'Monthly, no daily proration' : 'One-off'}</small></div><div><span>Expense in period</span><strong>{sourceMoney(item.periodAmountMinor, currency)}</strong><small>{formatDate(context.dateRange.from)} to {formatDate(context.dateRange.to)}</small></div><div><span>Allocated in selected context</span><strong>{sourceMoney(item.allocatedMinor, currency)}</strong></div><div><span>Unallocated in period</span><strong>{sourceMoney(item.unallocatedMinor, currency)}</strong></div></section>
    <div className="expense-tabs" role="tablist" aria-label="Expense detail tabs">{tabs.map((id, index) => <button key={id} id={`expense-tab-${id}`} role="tab" aria-selected={tab === id} aria-controls={`expense-panel-${id}`} tabIndex={tab === id ? 0 : -1} onClick={() => setTab(id)} onKeyDown={(event) => { let next = index; if (event.key === 'ArrowRight') next = (index + 1) % tabs.length; else if (event.key === 'ArrowLeft') next = (index + tabs.length - 1) % tabs.length; else if (event.key === 'Home') next = 0; else if (event.key === 'End') next = tabs.length - 1; else return; event.preventDefault(); setTab(tabs[next]); document.getElementById(`expense-tab-${tabs[next]}`)?.focus(); }}>{id[0].toUpperCase() + id.slice(1)}{id === 'history' ? ` (${item.versions.length})` : ''}</button>)}</div>
    <section role="tabpanel" id={`expense-panel-${tab}`} aria-labelledby={`expense-tab-${tab}`} tabIndex={0}>
      {tab === 'overview' ? <div className="expense-overview-grid"><section className="expense-panel"><h2>Expense overview</h2><dl className="expense-facts"><div><dt>Name</dt><dd>{item.expense.name}</dd></div><div><dt>Type</dt><dd>{item.expense.type === 'recurring' ? 'Recurring' : 'One-off'}</dd></div><div><dt>Category</dt><dd>{item.expense.category}</dd></div><div><dt>Sensitivity</dt><dd>{item.expense.sensitive ? 'Sensitive' : 'Standard'}</dd></div><div><dt>Scope</dt><dd>{scopeTypeLabel(item.version.scope.type)} · {item.scopeLabel}</dd></div><div><dt>Effective period</dt><dd>{expensePeriod(item)}</dd></div><div><dt>Recurrence</dt><dd>{item.version.recurrence ? `Monthly on billing day ${item.version.billingDay} (clamped for short months)` : 'One occurrence on the expense date'}</dd></div><div><dt>Updated by</dt><dd>{item.expense.updatedBy} · {formatDate(item.expense.updatedAt)}</dd></div></dl></section><section className="expense-panel"><h2>Financial basis & governance</h2><dl className="expense-facts"><div><dt>Source amount</dt><dd>{sourceMoney(item.version.amountMinor, item.version.currency)}</dd></div><div><dt>Allocation basis</dt><dd>{EXPENSE_ALLOCATION_BASIS}</dd></div><div><dt>Source</dt><dd>{item.version.source}</dd></div><div><dt>Reason</dt><dd>{item.version.reason}</dd></div><div><dt>Created by</dt><dd>{item.expense.createdBy} · {formatDate(item.expense.createdAt)}</dd></div></dl><p className="expense-context-note">Allocations are internal financial calculations. Source and reporting amounts below use the shared reporting-currency conversion.</p><Link className="expense-name" href={link('reports/expenses')}>Open Expense Report</Link></section></div> : null}
      {tab === 'allocation' ? <div className="expense-tab-stack"><section className="expense-panel"><h2>Allocation basis</h2><p>{EXPENSE_ALLOCATION_BASIS}. Positive Net Revenue weights are taken from eligible canonical transactions; rounding preserves each allocated occurrence total.</p><p>Allocated values below follow the selected Company, Marketplace, Account and reporting period. The configured expense amount can span a broader scope.</p></section><section className="expense-panel"><h2>Occurrences in the reporting period</h2>{item.occurrences.length ? <div className="expense-occurrences">{item.occurrences.map((occurrence) => <div key={occurrence.id}><span>{formatDate(occurrence.occurredAt)}</span><strong>{sourceMoney(occurrence.amountMinor, occurrence.currency)}</strong><span>Reporting amount {sourceMoney(expenseReportingMinor(occurrence), currency)}</span>{occurrence.currency !== currency ? <small>FX basis {occurrence.currency} → {currency}: {occurrence.amountMinor ? (expenseReportingMinor(occurrence) / occurrence.amountMinor).toFixed(4) : '—'}</small> : null}</div>)}</div> : <p>No occurrence falls within the current reporting period.</p>}</section><EnterpriseDataGrid data={item.allocations} columns={allocationColumns} ariaLabel="Expense allocations" canExport={false} initialPinnedColumns={['occurredOn']} mobileColumns={['occurredOn', 'product', 'allocatedMinor']} emptyTitle="No allocation in this context" emptyDescription="No eligible allocation is available for this reporting period and selected scope. Configured and unallocated amounts remain in the ledger." /></div> : null}
      {tab === 'history' ? <div className="expense-tab-stack"><Alert title="Effective-dated financial history">Earlier reporting periods retain their applicable version. Superseded evidence is preserved for review and is excluded from current calculations.</Alert><div className="expense-history">{item.versions.map((version) => <article className="expense-panel" key={version.id}><header><h2>{formatDate(version.effectiveFrom)} — {version.effectiveTo ? formatDate(shiftIsoDate(version.effectiveTo, -1)) : 'Ongoing'}</h2><Badge tone={version.supersededAt ? 'neutral' : 'info'}>{version.supersededAt ? 'Superseded evidence' : 'Applied version'}</Badge></header><strong className="expense-history-amount">{sourceMoney(version.amountMinor, version.currency)}{version.recurrence ? ' / month' : ''}</strong><dl className="expense-facts"><div><dt>Currency</dt><dd>{version.currency}</dd></div><div><dt>Scope</dt><dd>{scopeTypeLabel(version.scope.type)} · {scopeFor(version)}</dd></div><div><dt>Source</dt><dd>{version.source}</dd></div><div><dt>Reason</dt><dd>{version.reason}</dd></div><div><dt>Changed by</dt><dd>{version.changedBy} · {formatDate(version.createdAt)}</dd></div></dl></article>)}</div></div> : null}
      {tab === 'activity' ? <div className="expense-tab-stack"><p className="expense-context-note">Internal expense actions and preserved financial evidence.</p>{item.activity.length ? item.activity.map((event) => <article className="expense-panel expense-activity" key={event.id}><header><h2>{eventLabel(event.action)}</h2><time dateTime={event.occurredAt}>{formatDate(event.occurredAt, { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC' })} UTC</time></header><p>{actorName(event.newValue)} · {event.reason ?? 'No additional reason'}</p><details><summary>View previous and new evidence</summary><div className="expense-evidence"><section><h3>Previous value</h3><pre>{JSON.stringify(event.previousValue, (_key, value) => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(value) ? formatDate(value) : value, 2)}</pre></section><section><h3>New value</h3><pre>{JSON.stringify(event.newValue, (_key, value) => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(value) ? formatDate(value) : value, 2)}</pre></section></div></details></article>) : <EmptyState title="No internal actions recorded" description="Financial changes will appear here with actor, time, reason and evidence." />}</div> : null}
    </section>
    {editing && hook.query.data ? <ExpenseEditor item={item} workspace={hook.query.data} hook={hook} onClose={() => setEditing(false)} onSaved={() => { setEditing(false); showToast('Expense updated. History and audit evidence remain preserved.'); }} /> : null}
    {ending ? <EndExpenseDialog item={item} hook={hook} onClose={() => setEnding(false)} onSaved={() => { setEnding(false); showToast('Expense ended. Historical evidence remains available.'); }} /> : null}
  </div>;
}