import Link from 'next/link';
import { Check, ArrowUpRight } from 'lucide-react';
import { MarketingCTA } from './cta';

export type FAQItem = { question: string; answer: string };
export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="m-eyebrow"><span aria-hidden="true" />{children}</p>; }
export function FAQ({ items }: { items: FAQItem[] }) { return <section className="m-section m-faq" id="faq"><div><Eyebrow>A little more clarity</Eyebrow><h2>Good questions.<br />Straight answers.</h2><Link href="/contact" className="m-inline-link">Talk through your setup <ArrowUpRight size={16} /></Link></div><div>{items.map((item) => <details key={item.question}><summary>{item.question}<span aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section>; }
export function CTASection() { return <section className="m-final-cta" id="start"><div className="m-container"><Eyebrow>Make the numbers make sense</Eyebrow><h2>See where marketplace<br />profit really comes from.</h2><p>Bring your marketplace accounts and product costs into one explainable profitability workspace.</p><div className="m-actions"><MarketingCTA id="final-start-test-plan" /><MarketingCTA href="/contact" variant="secondary" id="final-contact">Talk to us</MarketingCTA></div><span className="m-small">Module 01 access through the Test Plan. Commercial pricing is being finalised.</span></div></section>; }
export function CheckList({ items }: { items: string[] }) { return <ul className="m-checklist">{items.map((item) => <li key={item}><Check size={17} aria-hidden="true" />{item}</li>)}</ul>; }
export function MarketplaceStrip() { return <div className="m-marketplaces" aria-label="Module 01 marketplaces">{[['Amazon', 'amazon'], ['eBay', 'ebay'], ['Temu', 'temu']].map(([name, slug]) => <Link href={`/integrations/${slug}`} key={slug}><span className={`m-channel-dot m-channel-${slug}`} />{name}<ArrowUpRight size={16} aria-hidden="true" /></Link>)}</div>; }
export function FinancialWaterfall() {
  const rows = [{ label: 'Revenue', value: 204800, width: 100 }, { label: 'Refunds', value: -8200, width: 4 }, { label: 'Net Revenue', value: 196600, width: 96 }, { label: 'COGS', value: -92100, width: 45 }, { label: 'Marketplace Fees', value: -28600, width: 14 }, { label: 'Advertising', value: -14200, width: 7 }, { label: 'Shipping', value: -9800, width: 5 }, { label: 'Other Costs', value: -5600, width: 3 }, { label: 'Net Profit', value: 46300, width: 23 }];
  let remaining = 100;
  return <div className="m-waterfall"><div className="m-visual-heading"><span>From revenue to the result</span><span>Example data · GBP</span></div><ol>{rows.map((row) => { if (row.value < 0) remaining -= row.width; return <li key={row.label} className={row.label === 'Net Profit' ? 'm-waterfall-total' : row.value > 0 ? 'm-waterfall-positive' : ''}><span>{row.label}</span><div className="m-waterfall-track"><span style={{ width: `${row.width}%`, marginLeft: `${row.value < 0 ? remaining : 0}%` }} /></div><strong>{row.value < 0 ? '−' : ''}£{Math.abs(row.value).toLocaleString('en-GB')}</strong></li>; })}</ol><p>Every deduction visible. Every result explainable.</p></div>;
}
export function CostHistory() { return <div className="m-cost-history"><div className="m-visual-heading"><span>One Product. A cost for each period.</span><span>Example data</span></div><div>{[['Jan – Mar', '£6.50'], ['Apr – Jul', '£6.90'], ['Aug onward', '£7.20']].map(([period, cost]) => <div key={period}><span>{period}</span><strong>{cost}</strong><small>Cost per unit</small></div>)}</div><p>A February sale keeps its £6.50 cost when August’s price changes.</p></div>; }
export function GroupExample() { return <div className="m-group-example"><div className="m-visual-heading"><span>Disposable Gloves</span><span>Example data</span></div><div className="m-group-basis"><div><span>Base quantity</span><strong>1,000 <small>gloves</small></strong></div><div><span>Base cost</span><strong>£100 <span aria-hidden="true">→</span> £110</strong></div><div><span>Base unit cost</span><strong>£0.10 <span aria-hidden="true">→</span> £0.11</strong></div></div><div className="m-group-packs">{[[25, '2.50', '2.75'], [50, '5.00', '5.50'], [100, '10.00', '11.00']].map(([pack, before, after]) => <div key={pack}><span>{pack} pack</span><div className="m-pack-lines" aria-hidden="true">{Array.from({ length: Number(pack) / 5 }).map((_, i) => <i key={i} />)}</div><span className="m-pack-cost">£{before} <span>→</span> <strong>£{after}</strong></span><small>Inherited COGS</small></div>)}</div><p>Base cost ÷ base quantity × Pack Quantity = inherited Product cost.</p><div className="m-group-note"><Check size={16} /> Applied from the new effective date. Historical costs preserved.</div></div>; }
