import type { ScreenshotKey } from '@/src/components/marketing/screenshot';
import type { FAQItem } from '@/src/components/marketing/sections';

export interface MarketingSection { title: string; body: string[]; bullets?: string[] }
export interface MarketingPage {
  slug: string; title: string; description: string; eyebrow: string; headline: string; intro: string;
  screenshot?: ScreenshotKey; sections: MarketingSection[]; workflow: { title: string; body: string }[];
  faq: FAQItem[]; relatedLinks: { href: string; label: string }[]; keywords: string[];
}
const section = (title: string, ...body: string[]): MarketingSection => ({ title, body });
const faq = (question: string, answer: string): FAQItem => ({ question, answer });
const link = (href: string, label: string) => ({ href, label });
const step = (title: string, body: string) => ({ title, body });
export const homeFAQ = [
  faq('Which marketplaces does Stock Supplies support?', 'Module 01 brings Amazon, eBay and Temu into the same marketplace profitability workspace. Analyse a combined view, an individual marketplace or an assigned Company and Marketplace Account.'),
  faq('How is Net Profit calculated?', 'Start with Revenue, subtract Refunds to reach Net Revenue, then deduct COGS, Marketplace Fees, Advertising, Shipping and Other Costs. If product costs are missing, the workspace identifies Known Net Profit and shows Profitability Coverage.'),
  faq('Where do product costs come from?', 'Add COGS through CSV or Excel imports, Paste from Excel, bulk editing or individual Product edits. Related pack-size Products can inherit COGS from an effective-dated Product Group cost.'),
  faq('Does changing a cost affect historical profit?', 'A new cost applies from its effective date. Sales before that date retain the cost valid for their sale date. An approved backdated correction can recalculate affected historical periods; it does not silently overwrite the entire history.'),
  faq('Can I work across multiple companies?', 'Yes. An Organisation can contain several Companies and Marketplace Accounts. Your role and assignments determine which context you can see and which actions you can take.'),
  faq('Can Copilot change financial data?', 'Copilot can explain data and prepare suggestions. Financial changes require an authorised human to review and approve them. Suggestions alone do not change profitability.'),
  faq('Is inventory management included?', 'Module 01 focuses on marketplace profitability, Products and cost management. Inventory, purchasing, warehouse operations and other commerce modules are planned as future platform extensions.'),
];

export const marketingPages: MarketingPage[] = [
  {
    slug: 'marketplace-profitability', title: 'Marketplace Profitability Software | Stock Supplies',
    description: 'Explain marketplace profit across Amazon, eBay and Temu. Bring revenue, refunds, COGS, fees, advertising and shipping into one clear calculation.',
    eyebrow: 'Marketplace Profitability', headline: 'Every cost accounted for. Every margin explained.',
    intro: 'A sales total tells you what moved. Stock Supplies connects that revenue to the costs behind it, so your next decision starts with an explainable profit figure.', screenshot: 'dashboard',
    sections: [
      section('Follow the number from Revenue to Net Profit.', 'Refunds reduce Revenue to Net Revenue. Product costs, marketplace fees, advertising, shipping and other costs then explain what remains. Keep those deductions visible instead of compressing them into a margin with no supporting detail.', 'The Dashboard brings the calculation and its components together. Move from the headline result to a product or marketplace comparison to investigate where a cost or revenue change comes from. Financial discussions can start with the same underlying definitions.'),
      section('Combine channels. Keep their differences visible.', 'Amazon, eBay and Temu belong in one comparison, but a combined total should not hide account performance. Use Company, Marketplace, Marketplace Account and date context to narrow the view without changing the meaning of the metrics.', 'Review the current period against the preceding equivalent period. Compare revenue, fees and Net Profit together: higher sales can coincide with weaker margins, and a smaller channel can still contribute valuable profit.'),
      section('An incomplete number should look incomplete.', 'A missing product cost is unknown, not zero. When COGS is incomplete, Known Net Profit represents the result from available costs and Profitability Coverage makes the gap visible. This keeps a product with missing COGS from appearing artificially attractive.', 'Data freshness is a separate part of the picture. Delayed sync, an authentication failure or a partial historical import can limit the source data. The workspace surfaces those conditions so teams can investigate before relying on a period comparison.'),
      section('Turn a margin question into a focused review.', 'Finance teams can review fees and cost coverage; Marketplace Managers can investigate the channels and accounts assigned to them. Management can read the combined view without changing the financial records behind it.', 'Use Products to find the items contributing to a result, then examine their Listings, cost history and marketplace performance. Copilot can help explain a movement in the current context. Decisions and financial approval remain with authorised people.'),
    ],
    workflow: [step('Choose your context', 'Select the Company, marketplace accounts and reporting period you need.'), step('Check completeness', 'Read Profitability Coverage and source freshness alongside the result.'), step('Explain the movement', 'Compare periods and marketplaces, then follow the detail into Products.')],
    faq: [faq('Does Revenue include the full profit calculation?', 'Revenue is the starting point. Refunds, COGS, fees, advertising, shipping and other costs are separate components that explain the route to Net Profit.'), faq('What happens when COGS is missing?', 'Stock Supplies labels the available result as Known Net Profit and shows coverage. Add or correct the missing costs through the COGS workflow before treating the figure as complete.'), faq('Can I compare one account with the combined picture?', 'Company, marketplace and Marketplace Account filters let you move between an authorised combined view and narrower account context. The same date and financial definitions apply.')],
    relatedLinks: [link('/product-profitability', 'Investigate Product profitability'), link('/cogs-management', 'Improve your cost coverage'), link('/marketplace-analytics', 'Compare marketplaces')], keywords: ['marketplace profit analytics', 'ecommerce profitability software', 'marketplace margin tracking'],
  },
  {
    slug: 'product-profitability', title: 'Product & SKU Profitability Analytics | Stock Supplies',
    description: 'Understand Product and SKU margins across marketplace Listings, with units, revenue, fees, effective-dated COGS and marketplace comparisons.',
    eyebrow: 'Product Profitability', headline: 'Find the Products behind your profit.',
    intro: 'One internal Product can sell through several marketplace Listings. Keep its identity, cost and commercial performance connected while you investigate each channel.', screenshot: 'product',
    sections: [
      section('One Product identity. Several marketplace Listings.', 'A Product is your company-owned internal record. A Marketplace Listing is the channel-specific representation of that Product. Keeping these concepts distinct avoids treating every listing as a different business item.', 'The Products workspace connects the internal identity with its authorised Listings. Product Detail gives teams a consistent place to review the Product, its cost and its marketplace performance without losing which Company owns it.'),
      section('Review unit economics alongside sales volume.', 'Units and Revenue show demand; COGS, fees and the remaining costs explain the quality of that demand. Read Net Profit and Margin alongside volume to find Products that sell well but contribute less than expected.', 'Use filters to focus a review on low-margin, loss-making or missing-COGS Products. Missing cost is a coverage problem rather than evidence of strong profit. The distinction matters when deciding which Products need financial attention.'),
      section('Compare the same Product across marketplaces.', 'A Product can have different commercial outcomes across Amazon, eBay and Temu. Marketplace comparisons bring the authorised channel performance into the same Product context, with the selected date range applied consistently.', 'Use trends and period comparisons to investigate when the result changed. Check whether a revenue movement, refund pattern, fee or cost adjustment explains the difference before making a broader conclusion about the Product.'),
      section('Keep the cost behind the margin traceable.', 'Product cost history records the cost that applies from each effective date. A valid direct Product cost takes precedence; where applicable, the Product can inherit a cost from its Product Group and Pack Quantity.', 'The cost source helps a reviewer understand the margin calculation. Follow a missing or incorrect cost into COGS Management for a governed correction. Product analysis stays connected to that process without turning a read-only review into an accidental financial edit.'),
    ], workflow: [step('Find the Product', 'Search internal identity and inspect linked marketplace Listings.'), step('Read the economics', 'Compare units, revenue, COGS, Net Profit and Margin in context.'), step('Investigate the cause', 'Check trends, marketplace differences and effective-dated cost history.')],
    faq: [faq('Is a Product the same as a marketplace Listing?', 'No. The internal Product is owned by a Company. Its marketplace Listings represent where it sells and retain channel-specific context.'), faq('Can pack-size Products share a cost basis?', 'Yes. Product Groups can calculate inherited COGS from a base cost, base quantity and each member’s Pack Quantity. A valid direct Product cost can override that inheritance.'), faq('Are stock levels and purchasing included here?', 'This workspace focuses on Product identity, marketplace profitability and cost. Inventory levels and purchasing operations are future platform work.')],
    relatedLinks: [link('/cogs-management', 'Manage the cost behind the margin'), link('/product-groups', 'Understand pack-size costing'), link('/marketplace-profitability', 'Return to the combined result')], keywords: ['SKU profitability', 'product profitability software', 'ecommerce product margin'],
  },
  {
    slug: 'cogs-management', title: 'Ecommerce COGS Management Software | Stock Supplies',
    description: 'Manage product COGS with effective dates, cost history, CSV and Excel imports, bulk edits, human approvals and an auditable financial workflow.',
    eyebrow: 'COGS Management', headline: 'Your marketplace knows the price. You know the cost.',
    intro: 'Bring the missing half of product profitability into the workspace. Turn supplier spreadsheets and individual cost changes into effective-dated, reviewed Product costs.', screenshot: 'cogs',
    sections: [
      section('Start with the cost data you already have.', 'Upload CSV or Excel files, paste a range from Excel, edit several Products together or update one Product. These entry points lead into the same costing rules, so a bulk update does not bypass the discipline of an individual edit.', 'Review the source columns, Product matches, currency and effective dates before applying changes. A spreadsheet may contain useful prices alongside ambiguous identifiers or missing dates. The import workflow gives those issues a visible place to be resolved.'),
      section('Changing today’s cost should not rewrite yesterday’s profit.', 'A cost has a value and an effective date. A Product that cost £6.50 from January to March can use £6.90 from April and £7.20 from August. The sale date determines which approved cost applies.', 'An approved backdated correction can change the affected historical results when that is the intended action. The workflow makes that consequence reviewable. A routine new supplier price does not silently replace every earlier cost record.'),
      section('Resolve anomalies before they become financial facts.', 'Duplicate rows, conflicting values, unmatched Products and unusual cost changes need attention. Review them before approval, together with the proposed change and the period it affects. An unresolved match should not become a guessed Product cost.', 'Copilot can assist with spreadsheet column mapping and Product-match suggestions. Its suggestions are preparation for human review. They do not approve the import, repair missing costs autonomously or apply financial changes on their own.'),
      section('Make approval and cost lineage part of the workflow.', 'The person preparing an import may have a different role from the person authorised to approve it. Keep proposed changes separate from approved costs, and make the approval decision explicit before the new values affect profitability.', 'Audit history connects a change to its source and effective date. Where a Product already inherits a Group cost, a direct Product change needs to be understood as an override. That context helps finance review a correction without losing the original costing basis.'),
    ], workflow: [step('Bring in costs', 'Use CSV, Excel, Paste from Excel, bulk editing or a single Product edit.'), step('Review the proposal', 'Map columns, confirm Product matches and resolve missing values or anomalies.'), step('Approve and apply', 'An authorised reviewer approves the financial change and its effective date.')],
    faq: [faq('Can I use historical supplier prices?', 'Yes. Effective-dated cost records allow different values to apply to different sale dates. A reviewed backdated correction recalculates the affected periods.'), faq('Does an import replace every Product cost?', 'Only the approved changes are applied. Review the matched Products, proposed values and effective dates first. A direct Product cost can take precedence over inherited Group COGS.'), faq('What if some Products have no cost?', 'They remain identifiable as missing COGS. Profitability Coverage and Known Net Profit show the limitation until valid costs are available.'), faq('Can Copilot approve a cost import?', 'No. It can help interpret columns and suggest matches, but an authorised human must approve financial changes.')],
    relatedLinks: [link('/product-groups', 'Maintain pack costs through Product Groups'), link('/product-profitability', 'See the effect on Product margins'), link('/integrations/amazon', 'Understand Amazon COGS')], keywords: ['ecommerce COGS software', 'Amazon COGS tracking', 'product cost management'],
  },
  {
    slug: 'product-groups', title: 'Pack-Size Product Costing & Inherited COGS | Stock Supplies',
    description: 'Enter one bulk cost, define pack quantities and calculate inherited COGS for linked Products, with effective dates and historical preservation.',
    eyebrow: 'Product Groups / Inherited COGS', headline: 'Buy in bulk. Sell in packs. Maintain the cost once.',
    intro: 'Group related pack-size Products under a company-level costing basis. Define the bulk cost and each Pack Quantity, then carry a consistent inherited cost into profitability.', screenshot: 'groups',
    sections: [
      section('Give related pack sizes a shared costing basis.', 'Disposable Gloves provides a practical example. A base quantity of 1,000 gloves at £100 gives a base unit cost of £0.10. A 25-pack inherits £2.50 COGS, a 50-pack £5.00 and a 100-pack £10.00.', 'Each member remains a Product with its own identity and marketplace Listings. The Group supplies a company-level cost basis; it does not replace those Products or merge their commercial performance into one indistinguishable SKU.'),
      section('Change the bulk cost with a clear effective date.', 'If the same 1,000 gloves cost £110 from a new date, the base unit cost becomes £0.11. The linked packs inherit £2.75, £5.50 and £11.00 respectively for that period.', 'Group costs remain effective-dated. Earlier sales retain the applicable historical basis, and membership history matters when resolving which Group and Pack Quantity applied. A new supplier price should not silently rewrite previous profitability.'),
      section('Keep room for a deliberate Product override.', 'A Product may need its own direct cost for a particular period. When a valid direct Product COGS record applies, it takes precedence over the inherited Group cost. The source should be visible so reviewers can understand the exception.', 'If neither a valid direct cost nor an applicable inherited cost exists, the cost is missing. It is not treated as free stock. That distinction flows through to Product coverage and Known Net Profit.'),
      section('Cost allocation with financial review.', 'Pack Quantity connects the bulk basis to each member’s cost. Review the proposed Group change, linked Products and effective date before applying the new financial values. Copilot can suggest likely Product Groups, while authorised people approve the costing decisions.', 'This is a costing relationship. It does not assemble physical packs, move inventory or define a warehouse bill of materials. Teams can use it to keep pack-size COGS consistent within the current profitability module.'),
    ], workflow: [step('Set the basis', 'Choose the Company, base quantity, bulk cost and effective date.'), step('Link the pack sizes', 'Assign related Products and define each member’s Pack Quantity.'), step('Review inheritance', 'Check calculated COGS and any direct Product overrides before approval.')],
    faq: [faq('How is inherited COGS calculated?', 'Base cost divided by base quantity gives base unit cost. Multiply that by the Product’s Pack Quantity to calculate its inherited COGS.'), faq('Does updating the Group change past sales?', 'A new cost applies from its effective date. Historical cost and membership records preserve the basis for earlier sales; an approved backdated correction can affect the corresponding earlier period.'), faq('Is this inventory packaging or a bill of materials?', 'No. Product Groups describe a shared cost basis for related Products. Physical packaging, inventory movements and warehouse operations are outside Module 01.'), faq('Can one Product use a different cost?', 'Yes. A valid direct Product cost takes precedence over the applicable inherited Group cost.')],
    relatedLinks: [link('/cogs-management', 'Explore the full COGS workflow'), link('/product-profitability', 'Review pack-size profitability')], keywords: ['pack size costing', 'inherited COGS', 'bulk product cost allocation'],
  },
  {
    slug: 'copilot', title: 'Contextual Marketplace Analytics Copilot | Stock Supplies',
    description: 'Get contextual help with profitability, cost imports, Product matches and Group suggestions. Authorised people retain financial approval.',
    eyebrow: 'Contextual Copilot', headline: 'A clearer explanation. A better-prepared next step.',
    intro: 'Ask about the numbers you are already looking at. Copilot helps explain performance and prepare cost work within the current Product, marketplace and Company context.', screenshot: 'copilot',
    sections: [
      section('Start with the context already on screen.', 'A question about profit means something different for one Product than it does for an entire Organisation. Copilot uses the current authorised context to make an explanation relevant to the Company, marketplace, account and date range in view.', 'Ask why profit changed, what contributes to a low margin or how marketplace performance compares. An explanation should point back to the underlying figures and their completeness, so the user can inspect the evidence instead of accepting an unexplained conclusion.'),
      section('Make a cost spreadsheet easier to review.', 'Cost imports can arrive with unfamiliar column names and inconsistent Product identifiers. Copilot can help interpret likely column meanings and suggest Product matches, bringing the proposed mapping into the import review workflow.', 'The user can accept or correct those suggestions. A likely match still needs review, and an unknown value should not become an invented cost. Financial data remains governed by the import validation and approval process.'),
      section('Surface questions worth investigating.', 'An unusual cost movement, a loss-making Product or a likely family of pack-size SKUs can be a useful starting point for a review. Copilot can surface anomalies and suggest Product Groups while retaining the surrounding business context.', 'These are suggestions about where to look and how to prepare work. They are not a guarantee that an anomaly is an error, a forecast of future performance or a substitute for the person responsible for the financial record.'),
      section('Human approval stays in the loop.', 'Copilot can explain and suggest. Financial changes still require authorised human approval. Draft proposals and suggested mappings do not change Product COGS or the profitability calculation just because they appear in a conversation.', 'Role permissions and Company or Marketplace Account assignments remain relevant to the interaction. The same separation between financial preparation, review and approval applies whether work began in the interface or with contextual assistance.'),
    ], workflow: [step('Open the relevant view', 'Choose the Product, reporting period or import you want to understand.'), step('Ask a focused question', 'Review an explanation or suggested mapping in that context.'), step('Check and decide', 'Verify the supporting data and use the authorised approval workflow for changes.')],
    faq: [faq('Is Copilot an autonomous finance agent?', 'No. It provides contextual explanations and suggestions. Authorised people remain responsible for financial review and approval.'), faq('Can it help with spreadsheet imports?', 'It can help map columns and suggest Product matches. Users review those proposals, resolve issues and approve financial changes through the COGS workflow.'), faq('Does a suggestion update my costs?', 'No. A suggestion or draft does not alter approved COGS or profitability. Financial changes require the appropriate human approval.')],
    relatedLinks: [link('/cogs-management', 'See governed cost imports'), link('/product-groups', 'Explore Product Group suggestions'), link('/security', 'Understand roles and approval')], keywords: ['AI ecommerce analytics', 'AI marketplace profitability', 'AI cost import assistant'],
  },
  {
    slug: 'marketplace-analytics', title: 'Amazon, eBay & Temu Marketplace Analytics | Stock Supplies',
    description: 'Compare Amazon, eBay and Temu in one marketplace analytics workspace. Review account performance, Product margins, cost coverage and sync health.',
    eyebrow: 'Combined Marketplace Analytics', headline: 'Three channels. The same financial language.',
    intro: 'Bring Amazon, eBay and Temu performance into a shared view, then focus on the marketplace or account that needs attention.', screenshot: 'dashboard',
    sections: [
      section('A combined view that still explains each channel.', 'Separate marketplace reports make it difficult to compare performance consistently. Module 01 brings Revenue, Refunds, COGS, fees and Net Profit into a common reporting model so each channel can be understood on the same basis.', 'Start with all authorised marketplaces for the overview. Switch to an individual marketplace or Marketplace Account when you need to explain a result. A combined figure is the beginning of the investigation, not a reason to hide the underlying channel detail.'),
      section('Amazon, eBay and Temu have dedicated context.', 'Amazon analysis includes the revenue, fee, refund, advertising and cost components represented in the workspace. eBay analysis connects sales, fees, Products and cost to the same profitability model. Temu sits alongside them with Product and account context.', 'Available data and freshness need to be read in context. These pages describe the current product workflows; they do not promise specific production API coverage, unrestricted historical data or identical datasets from every marketplace.'),
      section('Keep Company and account ownership visible.', 'A business can operate several Companies and more than one account on a marketplace. The Organisation, Company and Marketplace Account hierarchy keeps those boundaries visible as users move between combined and narrower views.', 'Role and assignment restrictions determine which records a person can analyse. A Marketplace Manager can focus on assigned channels, while finance and management can work with the broader context they are authorised to see.'),
      section('Read freshness before drawing a conclusion.', 'A delayed account can change the meaning of a comparison. Sync Health distinguishes account states and the last successful sync, making it easier to identify a source problem before mistaking it for a commercial trend.', 'Pair freshness with Profitability Coverage. Current sales data does not make a margin complete when COGS is missing, and complete Product costs do not fix a failed marketplace sync. Both deserve a visible place beside the result.'),
    ], workflow: [step('Connect the context', 'Organise Companies and Marketplace Accounts during onboarding.'), step('Compare performance', 'Review marketplaces with shared dates and financial definitions.'), step('Follow the detail', 'Inspect an account, Product or coverage issue behind the result.')],
    faq: [faq('Which marketplaces are in Module 01?', 'Amazon, eBay and Temu. Each has a dedicated public product page and marketplace context in the profitability workspace.'), faq('Can I see all marketplaces together?', 'Yes. The combined view covers the marketplaces and accounts allowed by your role and assignments, with filters for a narrower analysis.'), faq('Does a synced account mean profit is complete?', 'Not necessarily. Source freshness and COGS coverage are different checks. Read both before treating a profit figure as complete.')],
    relatedLinks: [link('/integrations/amazon', 'Amazon profitability'), link('/integrations/ebay', 'eBay profitability'), link('/integrations/temu', 'Temu profitability')], keywords: ['multi marketplace analytics', 'Amazon eBay Temu analytics', 'marketplace account performance'],
  },
  {
    slug: 'integrations/amazon', title: 'Amazon Profitability Analytics | Stock Supplies',
    description: 'Understand Amazon revenue, refunds, fees, advertising and Product COGS in an explainable seller profitability dashboard with account and sync context.',
    eyebrow: 'Marketplaces / Amazon', headline: 'Understand what your Amazon sales leave behind.',
    intro: 'Bring Amazon revenue into the same conversation as refunds, fees, advertising and Product cost. Follow the route from a busy sales period to the margin it actually contributes.', screenshot: 'amazon',
    sections: [
      section('See the cost components behind Amazon performance.', 'Amazon sales volume is useful context, but it does not account for everything a business spends. Read Revenue and orders alongside Refunds, COGS, Marketplace Fees, Advertising, Shipping and Other Costs in the profitability workspace.', 'The result is an explanation of what contributes to Net Profit. Compare the selected period with the preceding equivalent period, then inspect the components that moved. More sales and more profit are different outcomes and deserve separate attention.'),
      section('Bring your own acquisition costs into the calculation.', 'Your marketplace selling price is not the amount you paid for the Product. Add Product COGS through spreadsheet imports, Paste from Excel, individual edits or bulk editing, with effective dates that match the intended costing period.', 'Related pack-size Products can inherit costs from Product Groups. A valid direct Product cost can take precedence when an exception is needed. Missing costs remain visible through Profitability Coverage rather than being treated as zero.'),
      section('Move from the Amazon account to the Product.', 'Filter to Amazon, select an authorised Marketplace Account and keep the Company and date range in view. Product analysis connects the internal Product to its Amazon Listings and lets teams review units, revenue, fees, costs and margins.', 'If the same Product sells on eBay or Temu, use the wider marketplace comparison to understand how channel performance differs. The Product identity gives that discussion a consistent starting point across Listings.'),
      section('Know which data you are relying on.', 'Account status and the last successful sync help you recognise a delayed or incomplete source. Read those signals before interpreting a sudden change as a sales or margin trend.', 'Module 01 demonstrates Amazon account connection, sync visibility and profitability workflows. Specific production API permissions, data availability and operating arrangements must be confirmed during access discussions; this page does not claim a particular Amazon partner status.'),
    ], workflow: [step('Choose the Amazon account', 'Select the Company and authorised marketplace context.'), step('Check cost and sync coverage', 'Resolve missing COGS and account issues before relying on the total.'), step('Review contribution', 'Compare periods and follow the margin into individual Products.')],
    faq: [faq('Can I track Amazon COGS?', 'Yes. Manage effective-dated Product costs through imports and editing, or inherited Group COGS for related pack sizes.'), faq('Can I compare Amazon with eBay and Temu?', 'Yes. The combined marketplace view and Product comparisons support analysis across the authorised channel context.'), faq('Is every Amazon dataset guaranteed to be live?', 'No such guarantee is made here. The product exposes account connection and sync status, and specific production data coverage should be confirmed during access discussions.')],
    relatedLinks: [link('/marketplace-profitability', 'See the full profit calculation'), link('/cogs-management', 'Manage Amazon Product costs'), link('/product-profitability', 'Review SKU margins')], keywords: ['Amazon profitability software', 'Amazon profit analytics', 'Amazon seller profit dashboard'],
  },
  {
    slug: 'integrations/ebay', title: 'eBay Profitability Analytics | Stock Supplies',
    description: 'Connect eBay sales, fees, refunds and Product COGS to explainable profitability, with account filters, marketplace comparisons and sync visibility.',
    eyebrow: 'Marketplaces / eBay', headline: 'Put eBay sales and costs in the same picture.',
    intro: 'See how eBay sales translate into Product and account profitability. Keep fees, refunds and your own costs visible alongside the revenue figure.', screenshot: 'dashboard',
    sections: [
      section('Explain the difference between sales and contribution.', 'An eBay sales total shows demand. It does not, on its own, explain how fees, refunds and Product costs affected the period. Stock Supplies brings those components into the same financial model used across Module 01.', 'Review Net Profit and Margin alongside Revenue, orders and units. Where costs are incomplete, Known Net Profit and Profitability Coverage make that limitation explicit. An uncosted sale should not look like an unusually profitable one.'),
      section('Connect eBay Listings to internal Products.', 'Your Company-owned Product is distinct from the eBay Listing through which it sells. Product Detail links that identity to authorised Listings, cost history and marketplace performance so teams can investigate without losing the internal reference.', 'Review low-margin or loss-making Products, then check the cost source and reporting period. Products sold in several pack sizes can share an effective-dated Group cost basis while retaining their individual Listings and financial results.'),
      section('Compare accounts with consistent context.', 'Select eBay as the marketplace and narrow to the relevant Company or Marketplace Account. Shared financial definitions and date ranges help make the result comparable with the combined marketplace view.', 'Finance can investigate the cost components, while Marketplace Managers focus on the accounts assigned to them. The broader Amazon and Temu comparison is available within each user’s authorised scope rather than exposing unrelated Company records.'),
      section('Make connection issues visible.', 'An authentication failure or delayed sync can interrupt the data behind the report. Account status and Sync Health help distinguish those problems from changes in commercial performance, with last successful sync context available for review.', 'The current product demonstrates eBay connection and analytical workflows. Specific production authentication, API data coverage and historical availability need to be confirmed for deployment. The public page does not promise continuous live data or marketplace endorsement.'),
    ], workflow: [step('Select eBay context', 'Choose the Company, account and reporting dates.'), step('Review the full calculation', 'Read sales alongside fees, refunds and effective-dated COGS.'), step('Investigate Products', 'Follow margin differences into Listings, cost history and coverage.')],
    faq: [faq('Can I analyse more than one eBay account?', 'The Company and Marketplace Account model supports multiple accounts. Your role and assignments determine which accounts appear in your analysis.'), faq('How do my Product costs enter the eBay calculation?', 'Maintain COGS through CSV or Excel imports, Paste from Excel, individual or bulk edits, and applicable Product Group inheritance.'), faq('What if eBay authentication fails?', 'The workspace exposes connection and sync issues. Review the affected account and last successful sync before relying on its reporting period.')],
    relatedLinks: [link('/marketplace-profitability', 'Understand explainable profitability'), link('/product-profitability', 'Investigate eBay Product margins'), link('/cogs-management', 'Bring in your costs')], keywords: ['eBay profit analytics', 'eBay seller profitability', 'eBay profit tracking'],
  },
  {
    slug: 'integrations/temu', title: 'Temu Seller Profitability Analytics | Stock Supplies',
    description: 'Review Temu Product and account profitability alongside Amazon and eBay, with Product costs, financial coverage and marketplace sync context.',
    eyebrow: 'Marketplaces / Temu', headline: 'Give Temu a place in your profitability picture.',
    intro: 'Analyse Temu sales with Product cost and account context, then compare its contribution with your other authorised marketplaces.', screenshot: 'product',
    sections: [
      section('Understand contribution, beyond the sales total.', 'Temu belongs in the combined picture when a business sells across several marketplaces. Module 01 represents Temu within the same reporting model, connecting available revenue and cost components to Net Profit and Margin.', 'Use that shared model to ask consistent questions about commercial performance. Read the source coverage and the selected period alongside each figure, rather than assuming that every marketplace provides identical data or supports the same operating arrangements.'),
      section('Keep your own Product costs in the calculation.', 'Product acquisition costs are maintained inside Stock Supplies. Add direct COGS through the governed cost workflows, or inherit a cost from an applicable Product Group and Pack Quantity.', 'Effective dates determine which approved cost applies to a sale. If the Product has no valid cost for the period, that gap remains visible. Known Net Profit and Profitability Coverage help prevent missing COGS from overstating the confidence of the result.'),
      section('Compare the Product across channels.', 'The internal Product identity connects authorised marketplace Listings. Product profitability can therefore be reviewed in Temu context and compared with the Product’s Amazon or eBay performance where those Listings exist.', 'Narrow by Company, Marketplace Account and date range to keep the comparison relevant. Role and assignment restrictions continue to apply: a combined analytical view should only contain the Companies and accounts the person is allowed to access.'),
      section('Use source visibility to qualify the result.', 'Account connection and sync status are part of the workflow. A failed or delayed source should be visible beside the analysis, with the last successful sync providing context for what the report can currently tell you.', 'This page describes Temu profitability concepts demonstrated in Module 01. It does not claim advanced Temu advertising tools, specific production API coverage or unrestricted historical data. Confirm the required production datasets and connection arrangements during access discussions.'),
    ], workflow: [step('Set the Temu scope', 'Select the Company and Marketplace Account you want to review.'), step('Check Product costs', 'Read direct or inherited COGS and any coverage gaps.'), step('Compare contribution', 'Review available Temu performance within the combined marketplace picture.')],
    faq: [faq('Is Temu part of the combined view?', 'Yes. Temu is represented alongside Amazon and eBay in Module 01, subject to the user’s authorised Company and account scope.'), faq('Does this include advanced Temu advertising tools?', 'No advanced Temu advertising functionality is claimed. The page focuses on the available profitability, Product, cost and account workflows.'), faq('Can Temu Products inherit Group COGS?', 'An internal Product can inherit COGS through an applicable company-level Product Group. That cost basis is used when valid for the sale date and no direct Product cost takes precedence.')],
    relatedLinks: [link('/marketplace-profitability', 'See the profitability model'), link('/product-profitability', 'Compare Product performance'), link('/cogs-management', 'Maintain effective-dated costs')], keywords: ['Temu seller analytics', 'Temu profitability', 'Temu marketplace profit tracking'],
  },
  {
    slug: 'pricing', title: 'Stock Supplies Pricing & Module 01 Access', description: 'Explore Module 01 and Test Plan access. Commercial plans and pricing will be finalised after operational testing and operating-cost analysis.',
    eyebrow: 'Pricing & access', headline: 'Start with the module that makes the numbers clear.', intro: 'Marketplace Profitability & Analytics is Module 01 of Stock Supplies. The Test Plan provides the current access path while commercial plans are being finalised.',
    sections: [section('One focused module. A substantial working foundation.', 'Module 01 brings the profitability Dashboard, Products, historical COGS, spreadsheet imports, bulk edits, Product Groups and contextual Copilot into the same workspace. Amazon, eBay and Temu sit within a multi-company and Marketplace Account model.', 'Sync Health, role-based access, Company and account assignments, financial approval and audit context support how teams use those capabilities. The Test Plan follows the existing registration and onboarding journey.'), section('Commercial pricing is still being worked through.', 'Commercial pricing is being finalised through operational testing and operating-cost analysis. There are no final monthly prices, invented plan tiers or implied unlimited allowances on this page.', 'Start the Test Plan registration flow to explore the current access process, or contact us about the Companies, accounts and team roles you need. A final paid offer should be assessed against its actual terms when those are available.'), section('A modular platform with a clear current scope.', 'Future modules are intended to extend Stock Supplies into inventory, purchasing, warehouse operations, fulfilment, finance and automation. Those capabilities are planned, not included as live operational modules today.', 'Module entitlement is part of the platform foundation. The public website describes what Module 01 does now and keeps future commercial packaging separate from current product access.')],
    workflow: [step('Create your account', 'Use the approved Stock Supplies registration flow.'), step('Select Test Plan access', 'Continue through the existing Module 01 access steps.'), step('Build your workspace', 'Set up the Organisation, Companies, marketplaces, costs and team.')],
    faq: [faq('What is the final subscription price?', 'Commercial pricing has not been finalised. It will follow operational testing and operating-cost analysis.'), faq('Is the Test Plan a promise of a free commercial plan?', 'No. Test Plan is the current onboarding access concept. This page does not promise a free tier, a final price or future commercial terms.'), faq('Are future modules included today?', 'No. Current access focuses on Module 01: Marketplace Profitability & Analytics. Future modules are planned extensions.')], relatedLinks: [link('/marketplace-profitability', 'Explore Module 01'), link('/contact', 'Discuss your access needs'), link('/security', 'Read about access and approval')], keywords: ['Stock Supplies pricing', 'Module 01 access', 'Test Plan'],
  },
  {
    slug: 'security', title: 'Security, Permissions & Financial Approval | Stock Supplies', description: 'Understand Stock Supplies tenant context, roles, Company assignments, financial approval and audit principles, with clear production assurance boundaries.',
    eyebrow: 'Security & access', headline: 'The right context. The right permissions. A clear record.', intro: 'Financial work needs more than a shared login. Stock Supplies makes Organisation context, assigned access and human approval visible parts of the product.',
    sections: [section('Access follows the structure of the business.', 'An Organisation contains Companies and Marketplace Accounts. Role permissions and assignments determine which analytical context a user can see and which actions are available. Module entitlement is another part of access to the workspace.', 'These interface and domain boundaries help teams separate responsibilities. They describe the product’s access model, not an independent assurance that a prototype alone provides production-grade tenant isolation or infrastructure security.'), section('Separate financial preparation from approval.', 'Cost users can prepare work within their permissions, while authorised financial reviewers approve changes. Auditors remain read-only. The same approval boundary applies to Copilot suggestions: an explanation or proposed mapping does not itself change financial data.', 'Audit history records financial workflow context so a reviewer can trace changes and effective dates. Privileged platform administration has a separate workspace from the tenant’s day-to-day operational interface.'), section('Evaluate production controls before operational rollout.', 'Production authentication, secure provider connections, infrastructure controls, retention arrangements and data-processing terms require their own implementation and review. Ask about these requirements as part of access discussions for your business.', 'No certification, uptime guarantee or compliance badge is asserted here. The current site describes demonstrated access and approval principles and avoids presenting them as a completed independent security assessment.')],
    workflow: [step('Assign a role', 'Give each person the capabilities needed for their work.'), step('Limit operational scope', 'Choose the Companies and Marketplace Accounts they can access.'), step('Review financial changes', 'Use human approval and audit context for cost updates.')],
    faq: [faq('Does Stock Supplies claim security certifications?', 'No certifications or independent compliance attestations are claimed on this website.'), faq('Can an analyst change Product costs?', 'Read-oriented roles do not gain financial approval just by seeing a profitability report. Capabilities and assigned scope determine the permitted actions.'), faq('Can Copilot bypass approval?', 'No. Financial changes still require the authorised human approval workflow.')], relatedLinks: [link('/copilot', 'Read the Copilot approval boundary'), link('/cogs-management', 'See governed cost changes'), link('/contact', 'Discuss production requirements')], keywords: ['Stock Supplies security', 'financial approval', 'role based access'],
  },
  {
    slug: 'about', title: 'About Stock Supplies | Commerce Operations, Explained', description: 'Stock Supplies is being built as a modular commerce operations platform, starting with explainable marketplace profitability and Product cost management.',
    eyebrow: 'About Stock Supplies', headline: 'Commerce is connected. Its numbers should be, too.', intro: 'Stock Supplies is being built as a modular commerce operations platform for marketplace businesses. The first step is making profitability understandable and actionable.',
    sections: [section('Begin where the operational questions meet.', 'Marketplace teams track sales. Finance reviews fees, refunds and expenses. Cost teams maintain supplier prices in spreadsheets. Each view matters, but the commercial result depends on connecting them with a consistent Product and Company context.', 'Module 01 brings those questions into one profitability workspace. It connects marketplace revenue with Product costs, preserves effective-dated history and exposes the coverage behind a result.'), section('Clarity is a product requirement.', 'An unexplained margin is difficult to trust. A missing cost should remain visible, a delayed marketplace sync should have a status and a financial change should have an authorised reviewer.', 'Those principles shape the Dashboard, Products, COGS workflows, Product Groups and contextual Copilot. The aim is practical: see what sold, what it cost, what changed and what remains.'), section('A focused first module, with a wider direction.', 'Marketplace Profitability & Analytics is the current module. The wider platform is intended to connect Products and inventory, purchasing and suppliers, sales operations, warehousing, fulfilment, finance and automation over time.', 'Future modules are planned work. This website makes no claim that inventory, purchasing or warehouse operations are already available, and it does not invent a delivery timetable for them.')],
    workflow: [step('Explain profitability', 'Bring marketplace revenue and costs into the same view.'), step('Improve the cost foundation', 'Maintain reviewable, effective-dated Product and Group costs.'), step('Extend with purpose', 'Develop future modules around connected commerce workflows.')],
    faq: [faq('Who is Stock Supplies for?', 'Marketplace businesses and the finance, marketplace, cost and management teams responsible for understanding their commercial performance.'), faq('What is available in the current module?', 'Marketplace Profitability & Analytics, with Products, COGS Management, Product Groups, contextual Copilot, sync visibility and multi-company access foundations.'), faq('Where can I discuss my business requirements?', 'Use the Contact page to prepare an enquiry, or start the existing Test Plan registration flow to explore Module 01 access.')], relatedLinks: [link('/marketplace-profitability', 'Explore the first module'), link('/pricing', 'Understand Test Plan access'), link('/contact', 'Talk to us')], keywords: ['Stock Supplies', 'commerce operations platform'],
  },
  {
    slug: 'contact', title: 'Contact Stock Supplies | Module 01 Access & Enquiries', description: 'Tell Stock Supplies about your Companies, marketplaces and team. Prepare a Module 01 access, demo, partnership or general enquiry in the contact prototype.',
    eyebrow: 'Talk to us', headline: 'Let’s start with how your business works.', intro: 'Tell us which marketplaces you sell on, how your team manages costs and what you need to understand. A useful conversation starts with your operational context.',
    sections: [section('Bring the questions that matter to your team.', 'You may be consolidating several marketplace accounts, reviewing missing COGS or trying to keep pack-size costs consistent. Explain the problem and the people involved so the discussion can focus on a relevant workflow.', 'This contact experience saves an enquiry in this browser when local storage is available. It does not send an email or notify Stock Supplies. You can copy the completed enquiry for your own records after saving it.'), section('Explore Module 01 while preparing your questions.', 'The product pages show the profitability model, effective-dated cost workflows, Product Groups and Copilot’s human approval boundary. Pricing and access explains the current Test Plan without inventing final commercial terms.', 'For account creation, use Start Test Plan. It connects directly to the existing registration and onboarding flow rather than creating a separate public-site signup process.')], workflow: [], faq: [faq('Will this form send an email?', 'No. This is a frontend contact prototype. It saves the enquiry locally in your browser and clearly reports whether that save succeeded.'), faq('Where do I begin registration?', 'Use Start Test Plan to open the approved /auth/register journey. Sign in is a separate link for returning users.')], relatedLinks: [link('/pricing', 'Read about access and pricing'), link('/marketplace-profitability', 'Explore the product'), link('/security', 'Review access principles')], keywords: ['contact Stock Supplies', 'Module 01 enquiry'],
  },
];
export const publicPaths = ['/', ...marketingPages.map((page) => `/${page.slug}`)];
